// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_min_max_legend = "CgkImNymn4cbEAIQDQ"; // <GPGSID>
        public const string achievement_this_cant_be_happening = "CgkImNymn4cbEAIQAA"; // <GPGSID>
        public const string achievement_i_need_a_bigger_box = "CgkImNymn4cbEAIQCA"; // <GPGSID>
        public const string achievement_yup = "CgkImNymn4cbEAIQBA"; // <GPGSID>
        public const string achievement_i_cant_believe_this_is_happening = "CgkImNymn4cbEAIQAQ"; // <GPGSID>
        public const string achievement_time_to_start_a_collection = "CgkImNymn4cbEAIQBw"; // <GPGSID>
        public const string achievement_max = "CgkImNymn4cbEAIQDA"; // <GPGSID>
        public const string achievement_way_too_many = "CgkImNymn4cbEAIQEA"; // <GPGSID>
        public const string achievement_collection_complete = "CgkImNymn4cbEAIQCg"; // <GPGSID>
        public const string leaderboard_top_score = "CgkImNymn4cbEAIQFA"; // <GPGSID>
        public const string achievement_lucky_streak = "CgkImNymn4cbEAIQEg"; // <GPGSID>
        public const string achievement_i_need_a_second_bigger_box = "CgkImNymn4cbEAIQCQ"; // <GPGSID>
        public const string achievement_just_one_more_game = "CgkImNymn4cbEAIQAg"; // <GPGSID>
        public const string achievement_deep_pockets = "CgkImNymn4cbEAIQEQ"; // <GPGSID>
        public const string achievement_min = "CgkImNymn4cbEAIQCw"; // <GPGSID>
        public const string achievement_oo_shiny = "CgkImNymn4cbEAIQDg"; // <GPGSID>
        public const string achievement_maybe_too_good = "CgkImNymn4cbEAIQBg"; // <GPGSID>
        public const string achievement_too_many_shinies = "CgkImNymn4cbEAIQDw"; // <GPGSID>
        public const string achievement_this_is_too_much = "CgkImNymn4cbEAIQAw"; // <GPGSID>
        public const string achievement_getting_good_at_this = "CgkImNymn4cbEAIQBQ"; // <GPGSID>
        public const string achievement_shhh = "CgkImNymn4cbEAIQEw"; // <GPGSID>

}

